import type { Metadata } from 'next';
import Navbar from '../../components/navlayout';

// These styles apply to every route in the application
import '../styles/globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html>
        <body>
        <Navbar/>
        {children}
        </body>
    </html>

  )
}