import type { Metadata } from 'next';
import Navbar from '../../components/navlayout';
import PrelineScript from "../../components/PrelineScript"
import Card from '../../components/Card';
// These styles apply to every route in the application
import '../styles/globals.css'
import { Suspense } from 'react';
import DashboardSkeleton from '../../components/skeletons'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html>
        <body>
        <Suspense fallback={<DashboardSkeleton/>}>
        <Navbar/>
        
        {children}
        </Suspense>
        <PrelineScript />
        </body>
    </html>

  )
}